language: node_js
node_js:
  - "10"

addons:
  ssh_known_hosts: 178.128.194.146

cache:
  directories:
    - node_modules

branches:
  only:
    - master

jobs:
  include:
    - stage: build & deploy
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install sshpass
      install:
        - yarn
      script:
        - yarn webpack --mode production --env.WEDDINGS_ALBUM $WEDDINGS_ALBUM --env.FASHION_ALBUM $FASHION_ALBUM --env.COMMERCIAL_ALBUM $COMMERCIAL_ALBUM --env.CLIENT_ID $CLIENT_ID
        - yarn test
      deploy:
        provider: script
        script: bash ./deploy/script.sh
        skip_cleanup: true
        on:
          branch: master
