language: node_js
node_js:
  - "10"

addons:
  ssh_known_hosts: 194.67.217.78

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install sshpass

install:
  - yarn
  - yarn global add webpack-cli@3.1.2 webpack@4

script:
  - webpack --mode production --env.WEDDINGS_ALBUM $WEDDINGS_ALBUM --env.FASHION_ALBUM $FASHION_ALBUM --env.COMMERCIAL_ALBUM $COMMERCIAL_ALBUM --env.CLIENT_ID $CLIENT_ID
  - npm test
  - rm -rf ./node_modules && rm -rf ./.git
  - cd ..
  - tar -czf release.tar.gz tenter
  - sshpass -p $PASSWORD scp ./release.tar.gz $USERNAME@194.67.217.78:./release.tar.gz
  - sshpass -p $PASSWORD ssh $USERNAME:$PASSWORD@194.67.217.78 sh ./deploy.sh
