language: node_js
node_js:
  - "10"

addons:
  ssh_known_hosts: 194.67.218.117

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install sshpass

install:
  - npm i

script:
  - node ./node_modules/webpack-cli/bin/webpack.js --mode development --env.WEDDINGS_ALBUM $WEDDINGS_ALBUM --env.FASHION_ALBUM $FASHION_ALBUM --env.COMMERCIAL_ALBUM $COMMERCIAL_ALBUM --env.CLIENT_ID $CLIENT_ID
  - npm test
  - rm -rf ./node_modules
  - cd ..
  - tar -czf release.tar.gz tenter
  - sshpass -p $PASSWORD scp ./tenter.tar.gz $USERNAME@194.67.218.117:./release.tar.gz
  - sshpass -p $PASSWORD ssh $USERNAME:$PASSWORD@194.67.218.117 sh ./deploy.sh
