# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      REDESIGN_ALBUM: ${{ secrets.REDESIGN_ALBUM }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 10
        uses: actions/setup-node@v2
        with:
          node-version: 10.x
      - run: |
          yarn
          yarn webpack --config ./webpack.utils.config.ts --mode production --env.REDESIGN_ALBUM $REDESIGN_ALBUM --env.CLIENT_ID $CLIENT_ID
          yarn webpack --mode production
          yarn test
  deploy:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      # Runs a single command using the runners shell
      - name: Install sshpass
        run: apt-get install sshpass
      - name: Deploy to prod
        run: bash ./deploy/script.sh
